spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zrpdb
    username: root
    password: 'mysql'
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySqlDialect
      show-sql: true
      format_sql: true


